export const translations: any = {
    tr: {
        lobby_title: "Parti Odaları",
        lobby_sub: "Sesli sohbete katıl, eğlenceye başla! 🎙️",
        create_room: "Oda Kur",
        no_rooms: "Henüz aktif oda yok. İlk odayı sen kur!",
        join: "Katıl",
        follow: "Takip",
        following: "Takipte",
        followers: "Takipçiler",
        owner: "Oda Sahibi",
        viewers: "İzleyici",
        seats: "Koltuk",
        settings: "Ayarlar",
        leave_room: "Odadan Çık",
        delete_room: "Odayı Sil",
        room_name: "Oda İsmi",
        room_avatar: "Oda Arka Planı",
        save: "Kaydet",
        cancel: "Vazgeç",
        send: "Gönder",
        chat_placeholder: "Sohbete katıl...",
        mic_on: "Mikrofon Açık",
        mic_off: "Mikrofon Kapalı",
        cam_on: "Kamera Açık",
        cam_off: "Kamera Kapalı",
        sleeping: "Uykuda",
        dummy_full_msg: "Bu oda şu an dolu, lütfen başka bir odaya katılın.",
        share: "Paylaş",
        copy_link: "Bağlantıyı Kopyala",
        share_post: "Post Olarak Paylaş",
        help: "Yardım",
        faq: "Sıkça Sorulan Sorular",
        search: "Ara...",
        search_no_res: "Sonuç bulunamadı.",
        home: "Keşfet",
        chat: "Mesajlar",
        party: "Parti",
        profile: "Profil",
        discover: "Keşfet",
        notifications: "Bildirimler",
        search_user: "Kullanıcı ara...",
        no_new_notifications: "Yeni bildirim yok.",
        all: "Hepsi",
        popular: "Popüler",
        new: "Yeni",
        nearby: "Yakınlarda",
        fast_match: "Hızlı Eşleş",
        party_room: "Parti Odası",
        following_posts: "Takip Edilen",
        new_post: "Yeni Gönderi",
        share_thought: "Aklından geçenleri paylaş...",
        not_shared: "Paylaşım yapılamadı!",
        post_error: "Post atma hatası",
        find_soulmate: "Ruh eşini anında bul",
        live: "CANLI",
        open: "AÇIK",
        join_fun: "Eğlenceye hemen katıl",
        typewriter_1: "Tarzını yansıt ✨",
        typewriter_2: "Parti odalarına katıl 🎉",
        typewriter_3: "1v1 eşleş ⚡",
        add_image: "Resim Ekle",
        sharing: "Paylaşılıyor...",
        room_invite: "Oda Daveti",
        invites_you: "Sizi odaya davet ediyor!",
        room_owner: "Oda Sahibi",
        join_btn: "KATIL",
        anonymous: "Anonim",
        locked: "Kilitli",
        user_muted: "Bu kullanıcı susturuldu",
        leader: "LİDER",
        join_room: "Odaya katıl",
        create_your_room: "Odanı oluştur",
        build_team: "Ekibini kur",
        make_friends: "Yeni dostlar edin",
        start_chat: "Sohbete başla",
        seat_locked_msg: "Bu koltuk kilitli!",
        room_info: "Oda Bilgisi",
        room_layout: "Oda Düzeni",
        mention_user: "Kişiyi Etiketleme",
        room_settings: "Oda Ayarları",
        close: "Kapat",
        unfollow: "Takibi Bırak",
        announcement_placeholder: "Üyelere göstermek için bir duyuru yazın...",
        chat_settings: "Chat Ayarları",
        only_owner_can_change_settings: "Bu ayarları sadece oda sahibi değiştirebilir.",
        chat_slow_mode_desc: "Üyeler sohbete sadece 5 saniyede bir mesaj gönderebilir.",
        close_room_chat: "Oda Sohbetini Kapat",
        normal_members_cannot_send_msg: "Normal üyeler mesaj gönderemez.",
        share_room: "Odayı Paylaş",
        shared: "✅ Paylaşıldı",
        shared_desc: "Oda daveti akışta paylaşıldı!",
        people_in_room: "Odadakiler",
        your_message_optional: "Mesajınız (Opsiyonel)",
        slow_mode_active: "🕒 Yavaş Mod Aktif",
        wait_n_seconds_msg: "Yeni mesaj yazmak için ${remaining} saniye bekleyin.",
        chat_disabled_here: "Bu odada mesaj yazma kapalıdır",
        chat_placeholder_mention: "Sohbete katıl... (@bahset)",
        slow_mode: "Yavaş Mod (Slow Mode)",
        edit: "Düzenle",
        edit_profile: "Profili Düzenle",
        follow_back: "Geri Takip",
        room_announcement: "Oda Duyurusu",
        no_announcement_yet: "Henüz bir duyuru girilmemiş.",
        edit_announcement: "Duyuruyu Düzenle",
        new_friend_request_title: "Yeni Arkadaşlık İsteği! ❤️",
        new_friend_request_body: "${from} sana arkadaşlık isteği gönderdi.",
        new_follower_title: "Yeni Takipçi! 🎉",
        new_follower_body: "${from} seni takip etmeye başladı.",
        friend_accepted_title: "Arkadaşlık Kabul Edildi! 🤝",
        friend_accepted_body: "${from} arkadaşlık isteğini kabul etti. Artık mesajlaşabilirsiniz!",
        liked_post: "${from} paylaşımını beğendi ❤️",
        commented_on_post: "${from} yorum yaptı 💬",
        party_invite_title: "🎤 Parti Daveti!",
        party_invite_body: "${from} seni \"${roomName}\" odasına davet ediyor!",
        ongoing_room_title: "Canlı Odadasın: ${roomName}",
        ongoing_room_body: "Bağlantı devam ediyor. Odadan çıkmak için tıklayın.",
        finish_room: "Odayı Sonlandır",
        store_web_mode: "Web Modu (Eklenti Yok)",
        product_not_found: "Ürün bulunamadı",
        system_logs: "Sistem Logları",
        product_already_owned: "Ürün zaten satın alınmış. Profiliniz güncelleniyor...",
        cannot_purchase_status: "Şu an satın alınamaz. Durum:",
        check_logs: "Lütfen sistem loglarını kontrol edin.",
        error: "HATA",
        announcement_title: "Duyuru 📢",
        login_required: "Giriş yapmanız gerekiyor",
        cannot_send_request_to_self: "Kendinize istek gönderemezsiniz",
        friend_request_already_sent: "Zaten bir istek gönderilmiş",
        invalid_target_user: "Geçersiz hedef kullanıcı",
        follow_failed: "Takip işlemi başarısız oldu",
    },
    en: {
        lobby_title: "Party Rooms",
        lobby_sub: "Join voice chat and start the fun! 🎙️",
        create_room: "Create Room",
        no_rooms: "No active rooms yet. Be the first to create one!",
        join: "Join",
        follow: "Follow",
        following: "Following",
        followers: "Followers",
        owner: "Owner",
        viewers: "Viewers",
        seats: "Seats",
        settings: "Settings",
        leave_room: "Leave Room",
        delete_room: "Delete Room",
        room_name: "Room Name",
        room_avatar: "Room Background",
        save: "Save",
        cancel: "Cancel",
        send: "Send",
        chat_placeholder: "Join the conversation...",
        mic_on: "Mic On",
        mic_off: "Mic Off",
        cam_on: "Camera On",
        cam_off: "Camera Off",
        sleeping: "Sleeping",
        dummy_full_msg: "This room is currently full, please join another room.",
        share: "Share",
        copy_link: "Copy Link",
        share_post: "Share as Post",
        help: "Help",
        faq: "FAQ",
        search: "Search...",
        search_no_res: "No results found.",
        home: "Explore",
        chat: "Messages",
        party: "Party",
        profile: "Profile",
        discover: "Discover",
        notifications: "Notifications",
        search_user: "Search user...",
        no_new_notifications: "No new notifications.",
        all: "All",
        popular: "Popular",
        new: "New",
        nearby: "Nearby",
        fast_match: "Fast Match",
        party_room: "Party Room",
        following_posts: "Following",
        new_post: "New Post",
        share_thought: "Share your thoughts...",
        not_shared: "Could not share!",
        post_error: "Post error",
        find_soulmate: "Find your soulmate instantly",
        live: "LIVE",
        open: "OPEN",
        join_fun: "Join the fun now",
        typewriter_1: "Express your style ✨",
        typewriter_2: "Join party rooms 🎉",
        typewriter_3: "1v1 Match ⚡",
        add_image: "Add Image",
        sharing: "Sharing...",
        room_invite: "Room Invite",
        invites_you: "Invites you to the room!",
        room_owner: "Room Owner",
        join_btn: "JOIN",
        anonymous: "Anonymous",
        locked: "Locked",
        user_muted: "This user is muted",
        leader: "LEADER",
        join_room: "Join room",
        create_your_room: "Create your room",
        build_team: "Build your team",
        make_friends: "Make new friends",
        start_chat: "Start chatting",
        seat_locked_msg: "This seat is locked!",
        room_info: "Room Info",
        room_layout: "Room Layout",
        mention_user: "Mention User",
        room_settings: "Room Settings",
        close: "Close",
        unfollow: "Unfollow",
        announcement_placeholder: "Write an announcement to show members...",
        chat_settings: "Chat Settings",
        only_owner_can_change_settings: "Only the room owner can change these settings.",
        chat_slow_mode_desc: "Members can only send messages every 5 seconds.",
        close_room_chat: "Close Room Chat",
        normal_members_cannot_send_msg: "Normal members cannot send messages.",
        share_room: "Share Room",
        shared: "✅ Shared",
        shared_desc: "Room invite shared in the feed!",
        people_in_room: "People in Room",
        your_message_optional: "Your Message (Optional)",
        slow_mode_active: "🕒 Slow Mode Active",
        wait_n_seconds_msg: "Wait ${remaining} seconds to send a new message.",
        chat_disabled_here: "Chatting is disabled in this room",
        chat_placeholder_mention: "Join the chat... (@mention)",
        slow_mode: "Slow Mode",
        edit: "Edit",
        edit_profile: "Edit Profile",
        follow_back: "Follow Back",
        room_announcement: "Room Announcement",
        no_announcement_yet: "No announcement entered yet.",
        edit_announcement: "Edit Announcement",
        new_friend_request_title: "New Friend Request! ❤️",
        new_friend_request_body: "${from} sent you a friend request.",
        new_follower_title: "New Follower! 🎉",
        new_follower_body: "${from} started following you.",
        friend_accepted_title: "Friend Request Accepted! 🤝",
        friend_accepted_body: "${from} accepted your friend request. You can now chat!",
        liked_post: "${from} liked your post ❤️",
        commented_on_post: "${from} commented 💬",
        party_invite_title: "🎤 Party Invite!",
        party_invite_body: "${from} invites you to the \"${roomName}\" room!",
        ongoing_room_title: "Live in Room: ${roomName}",
        ongoing_room_body: "Connection is active. Click to leave room.",
        finish_room: "Finish Room",
        store_web_mode: "Web Mode (No Plugin)",
        product_not_found: "Product not found",
        system_logs: "System Logs",
        product_already_owned: "Product already owned. Your profile is being updated...",
        cannot_purchase_status: "Cannot purchase right now. Status:",
        check_logs: "Please check the system logs.",
        error: "ERROR",
        announcement_title: "Announcement 📢",
        login_required: "Login required",
        cannot_send_request_to_self: "You cannot send a request to yourself",
        friend_request_already_sent: "A request has already been sent",
        invalid_target_user: "Invalid target user",
        follow_failed: "Follow action failed",
    }
};

export type Language = 'tr' | 'en';

export const getLanguage = (): Language => {
    const saved = localStorage.getItem('app_lang');
    if (saved === 'tr' || saved === 'en') return saved;

    // Tarayıcı dilini kontrol et
    const browserLang = navigator.language.split('-')[0];
    if (browserLang === 'tr') return 'tr';

    return 'en'; // Varsayılan İngilizce
};

export const tGlobal = (key: string): string => {
    const lang = getLanguage();
    return translations[lang][key] || key;
};
